### ISSUE TITLE
Uncaught Error: Error getting application root path

### ISSUE THREAD

**Issue by queeniema** [IBMStreams/build-ibmstreams#4]
Steps to reproduce:

1. Put focus on a SPL file or any other file (ie, file is not selected in the Tree View)
2. Run any of the `Spl Build` commands through the Command Palette

**Atom**: 1.32.0 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.13.6
**Thrown From**: [build-ibmstreams](https://github.com/IBMStreams/build-ibmstreams) package 0.1.0

### Stack Trace

Uncaught Error: Error getting application root path

```
At /Users/queeniema/.atom/packages/build-ibmstreams/lib/spl-build-common.js:515

Error: Error getting application root path
    at Function.getApplicationRoot (/Users/queeniema/git/atom-build-spl/lib/spl-build-common.js:515:10)
    at Object.buildApp (/packages/build-ibmstreams/lib/spl-build.js:190:29)
    at HTMLElement.splBuildBuild (/packages/build-ibmstreams/lib/spl-build.js:58:40)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:345848)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:688762)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:853821)
    at SelectListView.didClickItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:851763)
    at ListItemView.onclick (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:850753)
    at ListItemView.didClick (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:854841)
```

### Commands

```
     -1:18 core:paste (input.hidden-input)
     -1:17.8.0 core:save (input.hidden-input)
     -1:16.9.0 command-palette:toggle (input.hidden-input)
     -1:16 editor:consolidate-selections (input.hidden-input)
     -1:16 core:cancel (input.hidden-input)
     -1:15.1.0 command-palette:toggle (input.hidden-input)
     -1:08.1.0 core:confirm (input.hidden-input)
     -1:08.1.0 spl-build:build (input.hidden-input)
     -0:59.2.0 spl-build:build-submit (span.name.icon.icon-file-text)
     -0:52.3.0 core:save (input.hidden-input)
     -0:49.6.0 editor:consolidate-selections (input.hidden-input)
     -0:49.6.0 core:cancel (input.hidden-input)
     -0:44.4.0 spl-build:build-submit (span.name.icon.icon-file-text)
  2x -0:19 command-palette:toggle (input.hidden-input)
     -0:08.1.0 core:backspace (input.hidden-input)
     -0:06.4.0 spl-build:build (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
build-ibmstreams 0.1.0 
cson 2.0.1 
ide-ibmstreams 0.1.0 
language-ibmstreams-spl 0.1.0 
streams-dark-syntax 0.1.0 
streams-light-syntax 0.2.0 
```

**Comment by guychris** [comment]
Fixed in the v0.4.0 release
