### ISSUE TITLE
Cannot read property 'connection' of undefined - Error occurred during REFRESH_TOOLKITS

### ISSUE THREAD

**Issue by markheger** [IBMStreams/build-ibmstreams#57]
After a while the following error messages appear in Atom
```
13:56:03
Cannot read property 'connection' of undefined
IBM Streams Build
13:56:04
Error occurred during REFRESH_TOOLKITS
IBM Streams Build
13:56:04
```

```
Cannot read property 'connection' of undefined
Error occurred during REFRESH_TOOLKITS
Hide Stack Trace
TypeError: Cannot read property 'connection' of undefined
    at Object.updateLspToolkits (/Users/hegermar/.atom/packages/ide-ibmstreams/lib/main.js:85:50)
    at Object.___default (/Users/hegermar/.atom/packages/build-ibmstreams/lib/spl-build.js:154:93)
    at sendLspNotification (/Users/hegermar/.atom/packages/build-ibmstreams/lib/message-handler-registry.js:36:30)
    at Object.refreshLspToolkits (/Users/hegermar/.atom/packages/build-ibmstreams/lib/util/streams-toolkits-utils.js:13:3)
    at TapSubscriber._tapNext (/Users/hegermar/.atom/packages/build-ibmstreams/lib/epics/index.js:438:36)
    at TapSubscriber._next (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/operators/tap.js:59:27)
    at TapSubscriber.Subscriber.next (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Object.complete (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/observable/forkJoin.js:58:40)
    at Object.wrappedComplete (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Subscriber.js:188:76)
    at SafeSubscriber.__tryOrUnsub (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.complete (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Subscriber.js:190:26)
    at Subscriber._complete (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Subscriber.js:96:26)
    at Subscriber.complete (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Subscriber.js:78:18)
    at DefaultIfEmptySubscriber._complete (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/operators/defaultIfEmpty.js:47:26)
    at DefaultIfEmptySubscriber.Subscriber.complete (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Subscriber.js:78:18)
    at MergeMapSubscriber._complete (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/operators/mergeMap.js:87:30)
    at MergeMapSubscriber.Subscriber.complete (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Subscriber.js:78:18)
    at Observable._subscribe (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/util/subscribeToArray.js:7:16)
    at Observable._trySubscribe (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Observable.js:30:22)
    at MergeMapOperator.call (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/operators/mergeMap.js:39:23)
    at Observable.subscribe (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Observable.js:25:31)
    at DefaultIfEmptyOperator.call (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/operators/defaultIfEmpty.js:27:23)
    at Observable.subscribe (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Observable.js:25:31)
    at _loop_1 (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/observable/forkJoin.js:45:35)
    at Observable._subscribe (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/observable/forkJoin.js:68:13)
    at Observable._trySubscribe (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Observable.js:44:25)
```

**Comment by markheger** [comment]
resolved in v1.0.1 VsCode IBM Streams
