### ISSUE TITLE
Submit failed with CP4D: Invalid URI

### ISSUE THREAD

**Issue by markheger** [IBMStreams/build-ibmstreams#70]
```
Invalid URI "/streams-build/instances/sample-streams/nbg3//toolkits"
```

```
Error occurred during REFRESH_TOOLKITS
Hide Stack Trace
Error: Invalid URI "/streams-build/instances/sample-streams/nbg3//toolkits"
    at Request.init (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/request/request.js:273:31)
    at new Request (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/request/request.js:127:8)
    at request (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/request/index.js:53:10)
    at /Users/hegermar/.atom/packages/build-ibmstreams/node_modules/request/index.js:100:12
    at Observable._subscribe (/Users/hegermar/.atom/packages/build-ibmstreams/lib/util/streams-rest-v5.js:385:5)
    at Observable._trySubscribe (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Observable.js:30:22)
    at DoOperator.call (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/operators/tap.js:32:23)
    at Observable.subscribe (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Observable.js:25:31)
    at MapOperator.call (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/operators/map.js:32:23)
    at Observable.subscribe (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Observable.js:25:31)
    at MapOperator.call (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/operators/map.js:32:23)
    at Observable.subscribe (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Observable.js:25:31)
    at MergeMapOperator.call (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/operators/mergeMap.js:39:23)
    at Observable.subscribe (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Observable.js:25:31)
    at DoOperator.call (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/operators/tap.js:32:23)
    at Observable.subscribe (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Observable.js:25:31)
    at MapOperator.call (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/operators/map.js:32:23)
    at Observable.subscribe (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Observable.js:25:31)
    at DoOperator.call (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/operators/tap.js:32:23)
    at Observable.subscribe (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Observable.js:25:31)
    at CatchOperator.call (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/operators/catchError.js:32:23)
    at Observable.subscribe (/Users/hegermar/.atom/packages/build-ibmstreams/node_modules/rxjs/internal/Observable.js:25:31)
    at Object.subscribeToResult (/Users/hegermar/.atom/p
```

**Comment by markheger** [comment]
resolved in VsCode IBM Streams 1.0.1
